export const asciiTable: Map<string, IASCII> = new Map([
  [" ", { DEC: 32, Char: " " }],
  ["!", { DEC: 33, Char: "!" }],
  ['"', { DEC: 34, Char: '"' }],
  ["#", { DEC: 35, Char: "#" }],
  ["$", { DEC: 36, Char: "$" }],
  ["%", { DEC: 37, Char: "%" }],
  ["&", { DEC: 38, Char: "&" }],
  ["'", { DEC: 39, Char: "'" }],
  ["(", { DEC: 40, Char: "(" }],
  [")", { DEC: 41, Char: ")" }],
  ["*", { DEC: 42, Char: "*" }],
  ["+", { DEC: 43, Char: "+" }],
  [",", { DEC: 44, Char: "," }],
  ["-", { DEC: 45, Char: "-" }],
  [".", { DEC: 46, Char: "." }],
  ["/", { DEC: 47, Char: "/" }],
  ["0", { DEC: 48, Char: "0" }],
  ["1", { DEC: 49, Char: "1" }],
  ["2", { DEC: 50, Char: "2" }],
  ["3", { DEC: 51, Char: "3" }],
  ["4", { DEC: 52, Char: "4" }],
  ["5", { DEC: 53, Char: "5" }],
  ["6", { DEC: 54, Char: "6" }],
  ["7", { DEC: 55, Char: "7" }],
  ["8", { DEC: 56, Char: "8" }],
  ["9", { DEC: 57, Char: "9" }],
  [":", { DEC: 58, Char: ":" }],
  [";", { DEC: 59, Char: ";" }],
  ["<", { DEC: 60, Char: "<" }],
  ["=", { DEC: 61, Char: "=" }],
  [">", { DEC: 62, Char: ">" }],
  ["?", { DEC: 63, Char: "?" }],
  ["@", { DEC: 64, Char: "@" }],
  ["A", { DEC: 65, Char: "A" }],
  ["B", { DEC: 66, Char: "B" }],
  ["C", { DEC: 67, Char: "C" }],
  ["D", { DEC: 68, Char: "D" }],
  ["E", { DEC: 69, Char: "E" }],
  ["F", { DEC: 70, Char: "F" }],
  ["G", { DEC: 71, Char: "G" }],
  ["H", { DEC: 72, Char: "H" }],
  ["I", { DEC: 73, Char: "I" }],
  ["J", { DEC: 74, Char: "J" }],
  ["K", { DEC: 75, Char: "K" }],
  ["L", { DEC: 76, Char: "L" }],
  ["M", { DEC: 77, Char: "M" }],
  ["N", { DEC: 78, Char: "N" }],
  ["O", { DEC: 79, Char: "O" }],
  ["P", { DEC: 80, Char: "P" }],
  ["Q", { DEC: 81, Char: "Q" }],
  ["R", { DEC: 82, Char: "R" }],
  ["S", { DEC: 83, Char: "S" }],
  ["T", { DEC: 84, Char: "T" }],
  ["U", { DEC: 85, Char: "U" }],
  ["V", { DEC: 86, Char: "V" }],
  ["W", { DEC: 87, Char: "W" }],
  ["X", { DEC: 88, Char: "X" }],
  ["Y", { DEC: 89, Char: "Y" }],
  ["Z", { DEC: 90, Char: "Z" }],
  ["[", { DEC: 91, Char: "[" }],
  ["\\", { DEC: 92, Char: "\\" }],
  ["]", { DEC: 93, Char: "]" }],
  ["^", { DEC: 94, Char: "^" }],
  ["_", { DEC: 95, Char: "_" }],
  ["`", { DEC: 96, Char: "`" }],
  ["a", { DEC: 97, Char: "a" }],
  ["b", { DEC: 98, Char: "b" }],
  ["c", { DEC: 99, Char: "c" }],
  ["d", { DEC: 100, Char: "d" }],
  ["e", { DEC: 101, Char: "e" }],
  ["f", { DEC: 102, Char: "f" }],
  ["g", { DEC: 103, Char: "g" }],
  ["h", { DEC: 104, Char: "h" }],
  ["i", { DEC: 105, Char: "i" }],
  ["j", { DEC: 106, Char: "j" }],
  ["k", { DEC: 107, Char: "k" }],
  ["l", { DEC: 108, Char: "l" }],
  ["m", { DEC: 109, Char: "m" }],
  ["n", { DEC: 110, Char: "n" }],
  ["o", { DEC: 111, Char: "o" }],
  ["p", { DEC: 112, Char: "p" }],
  ["q", { DEC: 113, Char: "q" }],
  ["r", { DEC: 114, Char: "r" }],
  ["s", { DEC: 115, Char: "s" }],
  ["t", { DEC: 116, Char: "t" }],
  ["u", { DEC: 117, Char: "u" }],
  ["v", { DEC: 118, Char: "v" }],
  ["w", { DEC: 119, Char: "w" }],
  ["x", { DEC: 120, Char: "x" }],
  ["y", { DEC: 121, Char: "y" }],
  ["z", { DEC: 122, Char: "z" }],
  ["{", { DEC: 123, Char: "{" }],
  ["|", { DEC: 124, Char: "|" }],
  ["}", { DEC: 125, Char: "}" }],
  ["~", { DEC: 126, Char: "~" }],
  ["€", { DEC: 8364, Char: "€" }],
  ["£", { DEC: 163, Char: "£" }],
  ["¥", { DEC: 165, Char: "¥" }],
  ["₴", { DEC: 8372, Char: "₴" }],
  ["₹", { DEC: 8377, Char: "₹" }],
  ["₩", { DEC: 8361, Char: "₩" }],
  ["₺", { DEC: 8378, Char: "₺" }],
  ["₦", { DEC: 8358, Char: "₦" }],
  ["₫", { DEC: 8363, Char: "₫" }],
]);

export interface IASCII{
 DEC: number; Char: string
}

export function getASCIIData(char: string):IASCII{
  switch (true) {
    case char.includes('dot'):
    case char.includes('poin'):
      return asciiTable.get('.');
    case char.includes('com'):
      return asciiTable.get(',');
    case char.includes('dol'):
      return asciiTable.get('$');
    case char.includes('eur'):
      return asciiTable.get('€');
    default:
      return asciiTable.get(char.charAt(0))!;
  }
}
